name: adyen_dropin
description: Flutter plugin to integrate Adyen DropIn UI for Android and iOS.
version: 0.10.0
homepage: https://github.com/intive-opensource/adyen_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: app.adyen.flutter_adyen
        pluginClass: FlutterAdyenPlugin
      ios:
        pluginClass: FlutterAdyenPlugin

